USE [Sis2000]
GO

/****** Objeto: Table [dbo].[adrecibos] Fecha de script: 1/10/2026 1:25:38 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[adrecibos](
	[crecibo] [numeric](19, 0) NOT NULL,
	[u_version] [char](1) NULL,
	[cnpoliza] [char](30) NULL,
	[cnrecibo] [char](30) NOT NULL,
	[cnfacfisc] [char](30) NULL,
	[crecibo_org] [numeric](20, 0) NULL,
	[cpoliza] [numeric](20, 0) NULL,
	[fanopol] [smallint] NULL,
	[fmespol] [tinyint] NULL,
	[cramo] [smallint] NULL,
	[itiponegocio] [char](2) NULL,
	[itipoprod] [char](2) NULL,
	[itipopol] [char](1) NULL,
	[iestadoren] [char](1) NULL,
	[cpoliza_mae] [numeric](20, 0) NULL,
	[ccerti_mae] [numeric](10, 0) NULL,
	[itiporec] [char](1) NULL,
	[imodcobro] [char](2) NULL,
	[cdoccob] [numeric](17, 0) NULL,
	[csucur] [smallint] NULL,
	[csucurrec] [smallint] NULL,
	[ccanalalt] [char](10) NULL,
	[cscanalalt] [char](10) NULL,
	[ctipocanal] [char](1) NULL,
	[cgestor] [varchar](50) NULL,
	[criesgo] [smallint] NULL,
	[ccerti] [numeric](10, 0) NULL,
	[cproces] [numeric](14, 0) NULL,
	[cserie_rea] [smallint] NULL,
	[casegurado] [numeric](12, 0) NULL,
	[ctenedor] [numeric](12, 0) NULL,
	[cbeneficiario] [numeric](12, 0) NULL,
	[cacreedor] [numeric](12, 0) NULL,
	[cfinanciera] [numeric](12, 0) NULL,
	[cplan] [char](6) NULL,
	[cproductor] [numeric](11, 0) NULL,
	[ctipoproductor] [smallint] NULL,
	[czonaprod] [smallint] NULL,
	[csupervisor] [numeric](12, 0) NULL,
	[crecaudador] [numeric](12, 0) NULL,
	[cregion] [smallint] NULL,
	[ccentserv] [smallint] NULL,
	[cmercado] [smallint] NULL,
	[cprofesion] [smallint] NULL,
	[cactividad] [numeric](8, 0) NULL,
	[cgrupoecono] [numeric](12, 0) NULL,
	[cempresa] [numeric](12, 0) NULL,
	[cpais] [smallint] NULL,
	[cestado] [smallint] NULL,
	[cciudad] [smallint] NULL,
	[ccorregi] [smallint] NULL,
	[cbarriada] [smallint] NULL,
	[czonpos] [numeric](10, 0) NULL,
	[cmoneda] [char](4) NULL,
	[ptasamon] [numeric](13, 6) NULL,
	[ptasamon_pago] [numeric](13, 6) NULL,
	[femision] [datetime] NULL,
	[fdesde] [datetime] NULL,
	[fhasta] [datetime] NULL,
	[fdesde_pol] [datetime] NULL,
	[fhasta_pol] [datetime] NULL,
	[fanulacion] [datetime] NULL,
	[itipoanul] [char](1) NULL,
	[ccausaanul] [smallint] NULL,
	[fcontab] [datetime] NULL,
	[fanomescont] [numeric](7, 0) NULL,
	[nlote] [numeric](11, 0) NULL,
	[iestcont] [char](1) NULL,
	[fcobro] [datetime] NULL,
	[fpago_aseg] [datetime] NULL,
	[iestadorec] [char](1) NULL,
	[ifinanciado] [bit] NULL,
	[fdevolucion] [datetime] NULL,
	[idevolucion] [char](1) NULL,
	[iformadevo] [char](1) NULL,
	[msumabruta] [numeric](17, 2) NULL,
	[msumabrutaext] [numeric](17, 2) NULL,
	[msumacoa] [numeric](17, 2) NULL,
	[msumacoaext] [numeric](17, 2) NULL,
	[msumaneta] [numeric](17, 2) NULL,
	[msumanetaext] [numeric](17, 2) NULL,
	[mprimabruta] [numeric](17, 2) NULL,
	[mprimabrutaext] [numeric](17, 2) NULL,
	[mprimacoa] [numeric](17, 2) NULL,
	[mprimacoaext] [numeric](17, 2) NULL,
	[pcoa] [numeric](9, 2) NULL,
	[mprimaneta] [numeric](17, 2) NULL,
	[mprimanetaext] [numeric](17, 2) NULL,
	[mprimabruta_emi] [numeric](17, 2) NULL,
	[mprimacoa_emi] [numeric](17, 2) NULL,
	[mprimaneta_emi] [numeric](17, 2) NULL,
	[pretcoa] [numeric](9, 2) NULL,
	[pbono] [numeric](9, 2) NULL,
	[mbono] [numeric](17, 2) NULL,
	[mbonoext] [numeric](17, 2) NULL,
	[pcomision] [numeric](9, 2) NULL,
	[mcomision] [numeric](17, 2) NULL,
	[mcomisionext] [numeric](17, 2) NULL,
	[mcompart] [numeric](17, 2) NULL,
	[mcompartext] [numeric](17, 2) NULL,
	[mprimareas] [numeric](17, 2) NULL,
	[mprimareasext] [numeric](17, 2) NULL,
	[mprimareas_c] [numeric](17, 2) NULL,
	[mprimareasext_c] [numeric](17, 2) NULL,
	[mprimareas_n] [numeric](17, 2) NULL,
	[mprimareasext_n] [numeric](17, 2) NULL,
	[mpret] [numeric](17, 2) NULL,
	[mpretext] [numeric](17, 2) NULL,
	[mpcedida] [numeric](17, 2) NULL,
	[mpcedidaext] [numeric](17, 2) NULL,
	[mpfp] [numeric](17, 2) NULL,
	[mpfpext] [numeric](17, 2) NULL,
	[potrosrec] [numeric](9, 2) NULL,
	[motrosrec] [numeric](17, 2) NULL,
	[motrosrecext] [numeric](17, 2) NULL,
	[potrosdes] [numeric](9, 2) NULL,
	[motrosdes] [numeric](17, 2) NULL,
	[motrosdesext] [numeric](17, 2) NULL,
	[pgastos] [numeric](9, 2) NULL,
	[mgastos] [numeric](17, 2) NULL,
	[mgastosext] [numeric](17, 2) NULL,
	[potrosgas] [numeric](9, 2) NULL,
	[motrosgas] [numeric](17, 2) NULL,
	[motrosgasext] [numeric](17, 2) NULL,
	[mgemi] [numeric](17, 2) NULL,
	[mgemiext] [numeric](17, 2) NULL,
	[pgemi] [numeric](9, 2) NULL,
	[mmontoneto] [numeric](17, 2) NULL,
	[mmontonetoext] [numeric](17, 2) NULL,
	[mimpuesto] [numeric](17, 2) NULL,
	[pimpuesto] [numeric](9, 2) NULL,
	[mimpuestoext] [numeric](17, 2) NULL,
	[mmontorec] [numeric](17, 2) NULL,
	[mmontorecext] [numeric](17, 2) NULL,
	[mabono] [numeric](17, 2) NULL,
	[mabonoext] [numeric](17, 2) NULL,
	[mmontoapag] [numeric](17, 2) NULL,
	[mmontoapagext] [numeric](17, 2) NULL,
	[fdesde_dev] [datetime] NULL,
	[fhasta_dev] [datetime] NULL,
	[mprimadev] [numeric](17, 2) NULL,
	[mprimadevext] [numeric](17, 2) NULL,
	[mprimadif] [numeric](17, 2) NULL,
	[mprimadifext] [numeric](17, 2) NULL,
	[fpago] [datetime] NULL,
	[mpagado] [numeric](17, 2) NULL,
	[mpagadoext] [numeric](17, 2) NULL,
	[mpendiente] [numeric](17, 2) NULL,
	[mpendientext] [numeric](17, 2) NULL,
	[mpagcoa] [numeric](17, 2) NULL,
	[mpagcoaext] [numeric](17, 2) NULL,
	[pinteres] [numeric](9, 2) NULL,
	[minteres] [numeric](17, 2) NULL,
	[minteresext] [numeric](17, 2) NULL,
	[xobserva] [char](150) NULL,
	[bobsimp] [char](1) NULL,
	[xobsimp] [char](150) NULL,
	[iestadoimp] [char](1) NULL,
	[cforcob] [smallint] NULL,
	[czona_cobro] [smallint] NULL,
	[cbanco] [numeric](12, 0) NULL,
	[cagenban] [numeric](12, 0) NULL,
	[xcuentabanc] [char](30) NULL,
	[itipocta] [char](1) NULL,
	[xtarjeta] [char](30) NULL,
	[itarjeta] [char](2) NULL,
	[idomicialiado] [char](1) NULL,
	[qcuotas] [smallint] NULL,
	[ifrecuencia] [char](1) NULL,
	[istatpcnd] [char](1) NULL,
	[fpcnd] [datetime] NULL,
	[cprog] [char](20) NULL,
	[cnrecibo_rel] [char](30) NULL,
	[ifuente] [char](10) NULL,
	[bok] [char](1) NULL,
	[cerror] [char](10) NULL,
	[fingreso] [datetime] NULL,
	[cusuario] [numeric](11, 0) NULL,
	[ccategoria] [smallint] NULL,
	[cusuarioauto] [numeric](11, 0) NULL,
	[ccategoriaauto] [smallint] NULL,
	[fultmod] [datetime] NULL,
	[cusuariomod] [numeric](11, 0) NULL,
	[ccategoriamod] [smallint] NULL,
 CONSTRAINT [adrecibos_pk] PRIMARY KEY CLUSTERED 
(
	[crecibo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

