USE [Sis2000]
GO

/****** Objeto: Table [dbo].[pcpoliza] Fecha de script: 1/10/2026 1:33:12 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[pcpoliza](
	[cpoliza] [numeric](19, 0) NOT NULL,
	[fanopol] [smallint] NOT NULL,
	[fmespol] [tinyint] NOT NULL,
	[u_version] [char](1) NULL,
	[cramo] [smallint] NULL,
	[itipoprod] [char](2) NULL,
	[istatpol] [char](1) NULL,
	[itipopol] [char](1) NULL,
	[iestado] [char](1) NULL,
	[itiporen] [char](1) NULL,
	[iperren] [smallint] NULL,
	[ccauren] [smallint] NULL,
	[iestadoren] [char](1) NULL,
	[itipovenprima] [char](1) NULL,
	[ipervenprima] [smallint] NULL,
	[iestadovenprima] [char](1) NULL,
	[icalculoprima] [char](1) NULL,
	[precargo] [numeric](11, 4) NULL,
	[premb_t] [numeric](11, 4) NULL,
	[premb_b] [numeric](11, 4) NULL,
	[fultprefact] [datetime] NULL,
	[fultfact] [datetime] NULL,
	[itipofact] [char](2) NULL,
	[iformafact] [char](1) NULL,
	[iedad] [char](1) NULL,
	[icalculoedad] [char](1) NULL,
	[csucur] [smallint] NULL,
	[cnpoliza] [char](30) NULL,
	[canalista] [numeric](11, 0) NULL,
	[cultcert] [numeric](11, 0) NULL,
	[ctenedor] [numeric](11, 0) NULL,
	[cfinanciera] [smallint] NULL,
	[itipoingreso] [char](1) NULL,
	[cproductor] [numeric](11, 0) NULL,
	[czonaprod] [smallint] NULL,
	[ctipoprod] [smallint] NULL,
	[csupervisor] [smallint] NULL,
	[cregion] [smallint] NULL,
	[ccentserv] [smallint] NULL,
	[cmercado] [smallint] NULL,
	[cactividad] [numeric](8, 0) NULL,
	[cgrupoeco] [smallint] NULL,
	[cempresa] [smallint] NULL,
	[cpais] [smallint] NULL,
	[cestado] [smallint] NULL,
	[cciudad] [smallint] NULL,
	[ccorregi] [smallint] NULL,
	[cbarriada] [smallint] NULL,
	[czonapos] [char](10) NULL,
	[cejecta] [numeric](11, 0) NULL,
	[crecaudador] [numeric](11, 0) NULL,
	[cmoneda] [char](4) NULL,
	[ptasamon] [numeric](13, 6) NULL,
	[forigen] [datetime] NULL,
	[fdesde] [datetime] NULL,
	[fhasta] [datetime] NULL,
	[fanulacion] [datetime] NULL,
	[itipoanul] [char](1) NULL,
	[canula] [smallint] NULL,
	[iorigen] [char](2) NULL,
	[xobserva] [varchar](255) NULL,
	[icoaseguro] [bit] NULL,
	[ifp] [bit] NULL,
	[cmonext] [bit] NULL,
	[iborrar] [bit] NULL,
	[icambren] [bit] NULL,
	[icambven] [bit] NULL,
	[icambfac] [bit] NULL,
	[msumamax] [numeric](17, 2) NULL,
	[pprima] [numeric](13, 6) NULL,
	[iviolar_plazos] [bit] NULL,
	[imod_recargo] [bit] NULL,
	[ndiasfactant] [smallint] NULL,
	[ifactextra] [bit] NULL,
	[icondparttit] [bit] NULL,
	[icondpartben] [bit] NULL,
	[icobextraplan] [bit] NULL,
	[pcomision] [numeric](11, 4) NULL,
	[mcomision] [numeric](17, 2) NULL,
	[mcomisionext] [numeric](17, 2) NULL,
	[mprimabruta] [numeric](17, 2) NULL,
	[mprimabrutaext] [numeric](17, 2) NULL,
	[pcoa] [smallint] NULL,
	[mprimacoa] [numeric](17, 2) NULL,
	[mprimacoaext] [numeric](17, 2) NULL,
	[pretcoa] [smallint] NULL,
	[mprimaneta] [numeric](17, 2) NULL,
	[mprimanetaext] [numeric](17, 2) NULL,
	[motrosdes] [numeric](17, 2) NULL,
	[motrosdesext] [numeric](17, 2) NULL,
	[motrosrec] [numeric](17, 2) NULL,
	[motrosrecext] [numeric](17, 2) NULL,
	[mgastos] [numeric](17, 2) NULL,
	[mgastosext] [numeric](17, 2) NULL,
	[motrosgas] [numeric](17, 2) NULL,
	[motrosgasext] [numeric](17, 2) NULL,
	[mgemi] [numeric](17, 2) NULL,
	[mgemiext] [numeric](17, 2) NULL,
	[mimpuesto] [numeric](17, 2) NULL,
	[mimpuestoext] [numeric](17, 2) NULL,
	[mabono] [numeric](17, 2) NULL,
	[mabonoext] [numeric](17, 2) NULL,
	[mpfp] [numeric](17, 2) NULL,
	[mpfpext] [numeric](17, 2) NULL,
	[iclasetar] [char](1) NULL,
	[ccanalalt] [char](10) NULL,
	[cprog] [char](20) NULL,
	[ifuente] [char](10) NULL,
	[bok] [char](1) NULL,
	[cerror] [char](10) NULL,
	[fingreso] [datetime] NULL,
	[cusuario] [numeric](11, 0) NULL,
	[cusuariomod] [numeric](11, 0) NULL,
	[cusuarioauto] [numeric](11, 0) NULL,
	[ccategoria] [smallint] NULL,
	[ccategoriamod] [smallint] NULL,
	[ccategoriaauto] [smallint] NULL,
	[fultmod] [datetime] NULL,
 CONSTRAINT [pcpoliza_pk] PRIMARY KEY CLUSTERED 
(
	[cpoliza] ASC,
	[fanopol] ASC,
	[fmespol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

